name             'custom_apache'
maintainer       'Chef Software'
maintainer_email 'marcelo.gobelli@comcast.net'
license          'Apache-2.0'
description      'Installs/Configures custom_apache'
long_description 'Installs/Configures custom_apache'
version          '0.1.0'
supports         'ubuntu'
issues_url       'https://github.com/learn-chef/custom_apache/issues'
source_url       'httsp://github.com/learn-name/custom_apache'
chef_version     '>= 12.7' if respond_to?(:chef_version)
