name             'custom_apache'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures custom_apache'
long_description 'Installs/Configures custom_apache'
version          '0.1.0'
